name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        backend: [CPU, CUDA, OPENCL]
        exclude:
          - os: macos-latest
            backend: CUDA
          - os: windows-latest
            backend: OPENCL

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up C++
      uses: actions/setup-cpp@v2
      with:
        cpp-version: '14'

    - name: Configure CMake
      run: cmake . -B build -DGGML_USE_${{ matrix.backend }}=ON

    - name: Build
      run: cmake --build build --config Release

    - name: Run tests
      run: |
        cd build
        ctest --output-on-failure